py_training/OldboyBBS2/OldboyBBS2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from bbs import  views
from  web_chat import urls as chat_urls
from web_qq import urls as web_qq_urls
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chat/', include(chat_urls)),
    url(r'^web_qq/', include(web_qq_urls)),
    url(r'^$', views.index ),
    url(r'^life/$', views.life, name='life' ),
    url(r'^tech/$', views.tech, name='tech' ),
    url(r'^1024/$', views.category1024, name='category1024' ),
    url(r'^article/(\d+)/$', views.article, name='article'),
    url(r'^article/create/$', views.create_bbs, name='create_bbs'),
    url(r'^login/$', views.account_login, name='login'),
    url(r'^latest_bbs_id/$',views.latest_bbs_id, name='get_latest_bbs_id'),


]

py_training/OldboyBBS2/web_qq/urls.py
from django.conf.urls import include, url

import views
urlpatterns = [
    url(r'^$', views.dashboard, name='web_qq_dashboard'),
    url(r'^send_msg/$',views.send_msg,name="qq_send_msg"),
    url(r'^get_msg/$',views.get_msg,name="qq_get_msg"),



]

py_training/OldboyBBS2/bbs/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.



class BBS(models.Model):
    title = models.CharField(max_length=254,unique=True)
    category = models.ForeignKey('Category')
    author = models.ForeignKey("UserProfile")
    content = models.TextField(max_length=100000)
    breif = models.TextField(max_length=512,default='none.....')

    head_img = models.ImageField(upload_to="upload/bbs_summary/")

    publish_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

class Comment(models.Model):
    bbs = models.ForeignKey('BBS')
    parent_comment = models.ForeignKey('Comment',blank=True,null=True,related_name='p_comment')
    user = models.ForeignKey('UserProfile')
    comment = models.TextField(max_length=1024)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.comment

class Thumb(models.Model):
    bbs = models.ForeignKey('BBS')
    action_choices = (('thumb_up','Thumb Up'), ('view_count',"View Count"))
    action = models.CharField(choices=action_choices,max_length=32)
    user = models.ForeignKey('UserProfile')

    def __unicode__(self):
        return "%s : %s" %(self.bbs.title,self.action)


class Category(models.Model):
    name = models.CharField(max_length=32,unique=True)
    enabled = models.BooleanField(default=True)
    def __unicode__(self):
        return self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=64)
    user_groups = models.ManyToManyField('UserGroup')

    friends = models.ManyToManyField("self")
    online = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

class UserGroup(models.Model):
    name = models.CharField(max_length=32,unique=True)

    def __unicode__(self):
        return self.name

py_training/OldboyBBS2/templates/1024.html
{% extends 'index.html' %}


{% block content-left %}

    1024

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

py_training/OldboyBBS2/templates/article.html
{% extends 'index.html' %}
{% load custom %}

{% block content-left %}

   <div class="bbs_title">
    <h3>{{ article.title }}</h3>

    <span>{{ article.author.name }}</span>
    <span>{{ article.publish_date }}</span>
    <span>点赞{{ article.thumb_set.select_related.count }}</span>
    <span>评论{{ article.comment_set.select_related.count }}</span>
   </div>

  <div class="bbs_content">
    {{ article.content |safe}}

  </div>

  <div class="bbs_comment_box">
    <div class="bbs_comment_sub">
        <textarea cols="100%" rows="5" name="comment">

        </textarea>

    </div>
    <div class="bbs_comment_list">
        {#% build_layer_comments comment_tree  %#}
        {%  build_comment_tree comment_tree %}


    </div>
  </div>

{% endblock %}


{% block bottom-js %}

    <script type="text/javascript">


    </script>

{% endblock %}

py_training/OldboyBBS2/templates/create_bbs.html
{% extends 'index.html' %}


{% block content-left %}

{% if new_article %}
    <h3>文章<{{ new_article.title }}>已创建成功,点击<a href="{% url 'article' new_article.id  %}">此处</a>查看！</h3>

{% else %}

     <form action="{% url 'create_bbs' %}" method="POST"  enctype="multipart/form-data"> {% csrf_token %}

    <input type="text"  name="title" class="form-control" placeholder="文章标题...">
    <input type="file" name="head_image" />

     <textarea name="content" id="content">


     </textarea>
     <input type="submit" class="btn btn-info" value="发布" />
     </form>

{% endif %}


{% endblock %}


{% block bottom-js %}
   <script type="text/javascript" src="/static/plugins/tinymce/js/tinymce/tinymce.min.js"></script>
   <script type="text/javascript">
        tinymce.init({
            selector: "#content",
            theme: "modern",
            //width: 300,
            height: 400,
            plugins: [
                 "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                 "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                 "save table contextmenu directionality emoticons template paste textcolor"
           ],
           content_css: "/static/plugins/tinymce/js/tinymce/skins/lightgray/content.css",
           toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons",
           style_formats: [
                {title: 'Bold text', inline: 'b'},
                {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                {title: 'Example 1', inline: 'span', classes: 'example1'},
                {title: 'Example 2', inline: 'span', classes: 'example2'},
                {title: 'Table styles'},
                {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
            ]

        });
   </script>

{% endblock %}

py_training/OldboyBBS2/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load custom %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <!-- Custom CSS -->
    <link href="/static/css/blog-post.css" rel="stylesheet">
    <link href="/static/css/custom.css" rel="stylesheet">
    <link href="/static/css/bootstrap.vertical-tabs.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head-css %}
    {% endblock %}

</head>

<body>
    {% csrf_token %}
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">XOXO</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul id="top_menu" class="nav navbar-nav">
                    <li>
                        <a href="/">全部</a>
                    </li>
                    <li>
                        <a href="{% url 'life' %}">生活</a>
                    </li>
                    <li>
                        <a href="{% url 'tech' %}">技术</a>
                    </li>
                    <li>
                        <a href="{% url 'category1024' %}">1024</a>
                    </li>
                    <li>
                        <a href="{% url 'chat' %}">聊天室</a>
                    </li>
                    <li>
                        <a href="{% url 'web_qq_dashboard' %}">WEB QQ</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="#">{{ request.user.userprofile.name }}</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">登录/注册</a>
                    </li>
                    {% endif %}

                </ul>

            </div>
            <!-- /.navbar-collapse -->

        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    {% block page-container %}
    <div class="container">
        {% block container %}
        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
                {% block content-left %}
                <!-- Blog Post -->
                <div class="hide new_bbs_reminder">
                <span> </span>条新消息入榜,点击查看
                </div>
                {% for article in articles %}

                <div bbs_id="{{ article.id }}" class="row bbs-summary-box ">
                    <div class="bbs-summary-box-img col-md-3">

                         <img src="/static/imgs/{{ article.head_img }}"/>
                    </div>
                    <div class="bbs-summary-box-summary">

                         <h4><a href="{%  url 'article' article.id %}" target="_blank">{{ article.title }}</a></h4>
                        <h3>{{ article.title | upper }}</h3>

                         <div class="bbs-summary-box-summary-btn">
                             <a href="#">{{ article.author.name }}</a>
                             <span class="glyphicon glyphicon-time"></span> {{ article.publish_date }}
                             <span class="glyphicon glyphicon-comment"></span> {{ article.comment_set.select_related.count }}
                             <span class="glyphicon glyphicon-star"></span> {{ article.thumb_set.select_related.count }}

                         </div>
                         <p>{{ article.breif }}</p>

                    </div>

                </div> <!-- end bbs-summary-box  -->

                <hr>
                {% endfor %}

                <div class="pagination">
                        {% if articles.number != articles.paginator.page_range.0 %}
                            <a href="?page=1"><span class="page_num">首页</span></a>
                        {% endif %}
                        {% for page_num in articles.paginator.page_range %}

                                {%  abs_compare  page_num articles.number %}

                        {% endfor %}
                        {% if articles.number != articles.paginator.page_range.last %}
                            <a href="?page={{ articles.paginator.page_range.last }}"><span class="page_num">最后页</span></a>
                        {% endif %}

                </div>



                {% endblock %}
            </div>


            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">
                {% block content-right %}
                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>
                {% endblock %}
            </div>

        </div>
        <!-- /.row -->

        <hr>
        {% endblock %}
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    {% endblock %}
    <!-- /.container -->

    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>
    {% block bottom-js %}
    <script type="text/javascript">
        $(document).ready(function(){

            refreshBlog = setInterval(function(){
                var latest_bbs_ele = $(".bbs-summary-box")[0];


                $.get("{% url 'get_latest_bbs_id' %}",function(callback){

                    var new_bbs_count = callback - $(latest_bbs_ele).attr("bbs_id");
                    if (new_bbs_count > 0){

                        $(".new_bbs_reminder").removeClass("hide");
                        $(".new_bbs_reminder span").html(new_bbs_count);
                    }
                });//end get

            },3000);

        });//end doc ready


    </script>

    {% endblock %}
<script type="text/javascript">

    $(document).ready(function(){

        $("#top_menu a").each(function(){

            if ($(this).attr("href") == "{{ request.path }}"){
                $(this).parent().addClass("active");
            };
        });//end each

        /*

        */






    });// end doc ready

</script>

</body>

</html>

py_training/OldboyBBS2/templates/life.html
{% extends 'index.html' %}


{% block content-left %}

    生活页

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

py_training/OldboyBBS2/templates/login.html
{% extends 'index.html' %}

{% block container %}
<div>
    <form method="post" action="{% url 'login' %}">{% csrf_token %}

        <input type="text" name="username" placeholder="username" />
        <input type="password" name="password" placeholder="password" />
        <input type="submit" value="Login" class="btn btn-success" />

    </form>

    <p style="color: red">{{ login_err }}</p>
</div>

{% endblock %}

py_training/OldboyBBS2/templates/tech.html
{% extends 'index.html' %}


{% block content-left %}

    technique

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}